### ISSUE TITLE
more missing words

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/mikhail-artsybashev_sanine_percy-pinkerton#2]
https://github.com/standardebooks/mikhail-artsybashev_sanine_percy-pinkerton/blob/1c5ec367bab5ce410548321110e9645c60fc3ab1/src/epub/text/chapter-2.xhtml#L149

"...gave no respite..." should be "...gave her no respite..."

"...something caused her..." should be "...something which caused her..."

https://archive.org/details/sanineart00artsuoft/page/24/mode/2up

**Comment by acabal** [comment]
Thanks, these should be fixed now! If you find more typos you can put them all into one single issue, that will be easier for me.
