### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/mikhail-artsybashev_sanine_percy-pinkerton#5]
https://github.com/standardebooks/mikhail-artsybashev_sanine_percy-pinkerton/blob/a972087d0ebad83efc4c541dc41d1f07e0991279/src/epub/text/chapter-20.xhtml#L58

"...as if soliloquising. If I had not..." should be "...as if soliloquising. “If I had not..." [missing quotation mark]

https://archive.org/details/sanineart00artsuoft/page/162/mode/2up

https://github.com/standardebooks/mikhail-artsybashev_sanine_percy-pinkerton/blob/a972087d0ebad83efc4c541dc41d1f07e0991279/src/epub/text/chapter-20.xhtml#L64

"...overwhelming her reproaches..." should be "...overwhelming her with reproaches..."

https://archive.org/details/sanineart00artsuoft/page/162/mode/2up

**Comment by acabal** [comment]
Thanks, these should be fixed now!
