### ISSUE TITLE
variety of issues

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/mikhail-artsybashev_sanine_percy-pinkerton#7]
https://github.com/standardebooks/mikhail-artsybashev_sanine_percy-pinkerton/blob/45a17aebce09ef463f9ae0de4f63e4cb4bd0c653/src/epub/text/chapter-29.xhtml#L13
"...a challenge fro Sarudine." should be "...a challenge from Sarudine."
https://archive.org/details/sanineart00artsuoft/page/218/mode/2up

https://github.com/standardebooks/mikhail-artsybashev_sanine_percy-pinkerton/blob/45a17aebce09ef463f9ae0de4f63e4cb4bd0c653/src/epub/text/chapter-35.xhtml#L90
"...that we might pluck out." should be "...that we might pluck them out."
https://archive.org/details/sanineart00artsuoft/page/264/mode/2up

https://github.com/standardebooks/mikhail-artsybashev_sanine_percy-pinkerton/blob/45a17aebce09ef463f9ae0de4f63e4cb4bd0c653/src/epub/text/chapter-38.xhtml#L156
"She smiled at her now curiosity."
This is a correct transcription of the book scan, but I can't help but feel this is probably meant to be "own curiosity" or "new curiosity"
https://archive.org/details/sanineart00artsuoft/page/288/mode/2up
A later printing corrects this to "own curiosity":
https://books.google.com/books/content?id=L4tDAQAAMAAJ&pg=PA289&img=1&zoom=3&hl=en&bul=1&sig=ACfU3U2QJrJL_uifAsPRuaomuYFV0kgmOQ&ci=28%2C1233%2C803%2C132&edge=0

https://github.com/standardebooks/mikhail-artsybashev_sanine_percy-pinkerton/blob/45a17aebce09ef463f9ae0de4f63e4cb4bd0c653/src/epub/text/chapter-43.xhtml#L33
"...an I shall get..." should be "...and I shall get..."
https://archive.org/details/sanineart00artsuoft/page/310/mode/2up

Also, my Kobo hyphenates Svarog-itsch whereas the book scans hyphenate it as Svaro-gitsch.
Dunno if that's something that can be or should be corrected with manual use of <code>&amp;shy;</code>

**Comment by acabal** [comment]
Thanks! Hyphenation is left up to the reading device, we don't insert shy hyphens.
